# Generated by Django 4.2.6 on 2023-10-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.BigIntegerField(default=1)),
                ('service', models.IntegerField(default=1)),
                ('quantity', models.BigIntegerField(default=1)),
                ('link', models.URLField(max_length=300)),
                ('posts', models.TextField(blank=True, null=True)),
                ('list', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
