# Generated by Django 4.2.6 on 2023-10-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_task_order_user_id_alter_order_order_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_id',
            field=models.CharField(default=1, max_length=255, null=True, unique=True),
        ),
    ]
