# Generated by Django 4.2.6 on 2023-10-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_order_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='link',
        ),
        migrations.AddField(
            model_name='order',
            name='nickname',
            field=models.TextField(default='', max_length=150),
        ),
    ]
