# Generated by Django 4.2.6 on 2023-10-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_order_link_order_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='QiwiPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billid', models.CharField(default=1, max_length=100, unique=True)),
                ('amount_currency', models.TextField(default='RUB', max_length=10)),
                ('amount_value', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
