# Generated by Django 4.2.6 on 2023-10-25 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_qiwipayment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qiwipayment',
            name='amount_currency',
        ),
    ]
